# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude:
    - "(const|func|method|struct field|type|var) .* should be "
  exclude-use-default: false
  exclude-rules:
    - linters: [gosec]
      text: G304
    - path: generator/internal/model
      linters: [golint]
      test: should have comment or be unexported
    - path: _test\.go
      linters:
        - dupl
        - gosec
  max-same-issues: 0
  max-issues-per-linter: 0
linters:
  enable:
    - golint
    - gosec
    - interfacer
    - unconvert
    - gocyclo
    - goimports
    - gocritic
    - gofumpt
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - diagnostic
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 15
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
