// Code generated by octo-go; DO NOT EDIT.

package octo

import (
	"context"
	"fmt"
	components "github.com/willabides/octo-go/components"
	"net/http"
	"net/url"
)

/*
InteractionsGetRestrictionsForOrg performs requests for "interactions/get-restrictions-for-org"

Get interaction restrictions for an organization.

  GET /orgs/{org}/interaction-limits

https://developer.github.com/v3/interactions/orgs/#get-interaction-restrictions-for-an-organization
*/
func InteractionsGetRestrictionsForOrg(ctx context.Context, req *InteractionsGetRestrictionsForOrgReq, opt ...RequestOption) (*InteractionsGetRestrictionsForOrgResponse, error) {
	if req == nil {
		req = new(InteractionsGetRestrictionsForOrgReq)
	}
	resp := &InteractionsGetRestrictionsForOrgResponse{request: req}
	r, err := doRequest(ctx, req, "interactions/get-restrictions-for-org", opt...)
	if r != nil {
		resp.response = *r
	}
	if err != nil {
		return resp, err
	}
	resp.Data = components.InteractionLimit{}
	err = r.decodeBody(&resp.Data, "interactions/get-restrictions-for-org")
	if err != nil {
		return nil, err
	}
	return resp, nil
}

/*
InteractionsGetRestrictionsForOrg performs requests for "interactions/get-restrictions-for-org"

Get interaction restrictions for an organization.

  GET /orgs/{org}/interaction-limits

https://developer.github.com/v3/interactions/orgs/#get-interaction-restrictions-for-an-organization
*/
func (c Client) InteractionsGetRestrictionsForOrg(ctx context.Context, req *InteractionsGetRestrictionsForOrgReq, opt ...RequestOption) (*InteractionsGetRestrictionsForOrgResponse, error) {
	return InteractionsGetRestrictionsForOrg(ctx, req, append(c, opt...)...)
}

/*
InteractionsGetRestrictionsForOrgReq is request data for Client.InteractionsGetRestrictionsForOrg

https://developer.github.com/v3/interactions/orgs/#get-interaction-restrictions-for-an-organization
*/
type InteractionsGetRestrictionsForOrgReq struct {
	_url string
	Org  string

	/*
	The Interactions API is currently in public preview. See the [blog
	post](https://developer.github.com/changes/2018-12-18-interactions-preview)
	preview for more details. To access the API during the preview period, you must
	set this to true.
	*/
	SombraPreview bool
}

func (r *InteractionsGetRestrictionsForOrgReq) url() string {
	return r._url
}

func (r *InteractionsGetRestrictionsForOrgReq) urlPath() string {
	return fmt.Sprintf("/orgs/%v/interaction-limits", r.Org)
}

func (r *InteractionsGetRestrictionsForOrgReq) method() string {
	return "GET"
}

func (r *InteractionsGetRestrictionsForOrgReq) urlQuery() url.Values {
	query := url.Values{}
	return query
}

func (r *InteractionsGetRestrictionsForOrgReq) header(requiredPreviews, allPreviews bool) http.Header {
	headerVals := map[string]*string{"accept": String("application/json")}
	previewVals := map[string]bool{"sombra": r.SombraPreview}
	if requiredPreviews {
		previewVals["sombra"] = true
	}
	if allPreviews {
		previewVals["sombra"] = true
	}
	return requestHeaders(headerVals, previewVals)
}

func (r *InteractionsGetRestrictionsForOrgReq) body() interface{} {
	return nil
}

func (r *InteractionsGetRestrictionsForOrgReq) dataStatuses() []int {
	return []int{200}
}

func (r *InteractionsGetRestrictionsForOrgReq) validStatuses() []int {
	return []int{200}
}

// HTTPRequest builds an *http.Request
func (r *InteractionsGetRestrictionsForOrgReq) HTTPRequest(ctx context.Context, opt ...RequestOption) (*http.Request, error) {
	return buildHTTPRequest(ctx, r, "interactions/get-restrictions-for-org", opt)
}

/*
Rel updates this request to point to a relative link from resp. Returns false if
the link does not exist. Handy for paging.
*/
func (r *InteractionsGetRestrictionsForOrgReq) Rel(link RelName, resp *InteractionsGetRestrictionsForOrgResponse) bool {
	u := resp.RelLink(link)
	if u == "" {
		return false
	}
	r._url = u
	return true
}

/*
InteractionsGetRestrictionsForOrgResponse is a response for InteractionsGetRestrictionsForOrg

https://developer.github.com/v3/interactions/orgs/#get-interaction-restrictions-for-an-organization
*/
type InteractionsGetRestrictionsForOrgResponse struct {
	response
	request *InteractionsGetRestrictionsForOrgReq
	Data    components.InteractionLimit
}

/*
InteractionsGetRestrictionsForRepo performs requests for "interactions/get-restrictions-for-repo"

Get interaction restrictions for a repository.

  GET /repos/{owner}/{repo}/interaction-limits

https://developer.github.com/v3/interactions/repos/#get-interaction-restrictions-for-a-repository
*/
func InteractionsGetRestrictionsForRepo(ctx context.Context, req *InteractionsGetRestrictionsForRepoReq, opt ...RequestOption) (*InteractionsGetRestrictionsForRepoResponse, error) {
	if req == nil {
		req = new(InteractionsGetRestrictionsForRepoReq)
	}
	resp := &InteractionsGetRestrictionsForRepoResponse{request: req}
	r, err := doRequest(ctx, req, "interactions/get-restrictions-for-repo", opt...)
	if r != nil {
		resp.response = *r
	}
	if err != nil {
		return resp, err
	}
	resp.Data = components.InteractionLimit{}
	err = r.decodeBody(&resp.Data, "interactions/get-restrictions-for-repo")
	if err != nil {
		return nil, err
	}
	return resp, nil
}

/*
InteractionsGetRestrictionsForRepo performs requests for "interactions/get-restrictions-for-repo"

Get interaction restrictions for a repository.

  GET /repos/{owner}/{repo}/interaction-limits

https://developer.github.com/v3/interactions/repos/#get-interaction-restrictions-for-a-repository
*/
func (c Client) InteractionsGetRestrictionsForRepo(ctx context.Context, req *InteractionsGetRestrictionsForRepoReq, opt ...RequestOption) (*InteractionsGetRestrictionsForRepoResponse, error) {
	return InteractionsGetRestrictionsForRepo(ctx, req, append(c, opt...)...)
}

/*
InteractionsGetRestrictionsForRepoReq is request data for Client.InteractionsGetRestrictionsForRepo

https://developer.github.com/v3/interactions/repos/#get-interaction-restrictions-for-a-repository
*/
type InteractionsGetRestrictionsForRepoReq struct {
	_url  string
	Owner string
	Repo  string

	/*
	The Interactions API is currently in public preview. See the [blog
	post](https://developer.github.com/changes/2018-12-18-interactions-preview)
	preview for more details. To access the API during the preview period, you must
	set this to true.
	*/
	SombraPreview bool
}

func (r *InteractionsGetRestrictionsForRepoReq) url() string {
	return r._url
}

func (r *InteractionsGetRestrictionsForRepoReq) urlPath() string {
	return fmt.Sprintf("/repos/%v/%v/interaction-limits", r.Owner, r.Repo)
}

func (r *InteractionsGetRestrictionsForRepoReq) method() string {
	return "GET"
}

func (r *InteractionsGetRestrictionsForRepoReq) urlQuery() url.Values {
	query := url.Values{}
	return query
}

func (r *InteractionsGetRestrictionsForRepoReq) header(requiredPreviews, allPreviews bool) http.Header {
	headerVals := map[string]*string{"accept": String("application/json")}
	previewVals := map[string]bool{"sombra": r.SombraPreview}
	if requiredPreviews {
		previewVals["sombra"] = true
	}
	if allPreviews {
		previewVals["sombra"] = true
	}
	return requestHeaders(headerVals, previewVals)
}

func (r *InteractionsGetRestrictionsForRepoReq) body() interface{} {
	return nil
}

func (r *InteractionsGetRestrictionsForRepoReq) dataStatuses() []int {
	return []int{200}
}

func (r *InteractionsGetRestrictionsForRepoReq) validStatuses() []int {
	return []int{200}
}

// HTTPRequest builds an *http.Request
func (r *InteractionsGetRestrictionsForRepoReq) HTTPRequest(ctx context.Context, opt ...RequestOption) (*http.Request, error) {
	return buildHTTPRequest(ctx, r, "interactions/get-restrictions-for-repo", opt)
}

/*
Rel updates this request to point to a relative link from resp. Returns false if
the link does not exist. Handy for paging.
*/
func (r *InteractionsGetRestrictionsForRepoReq) Rel(link RelName, resp *InteractionsGetRestrictionsForRepoResponse) bool {
	u := resp.RelLink(link)
	if u == "" {
		return false
	}
	r._url = u
	return true
}

/*
InteractionsGetRestrictionsForRepoResponse is a response for InteractionsGetRestrictionsForRepo

https://developer.github.com/v3/interactions/repos/#get-interaction-restrictions-for-a-repository
*/
type InteractionsGetRestrictionsForRepoResponse struct {
	response
	request *InteractionsGetRestrictionsForRepoReq
	Data    components.InteractionLimit
}

/*
InteractionsRemoveRestrictionsForOrg performs requests for "interactions/remove-restrictions-for-org"

Remove interaction restrictions for an organization.

  DELETE /orgs/{org}/interaction-limits

https://developer.github.com/v3/interactions/orgs/#remove-interaction-restrictions-for-an-organization
*/
func InteractionsRemoveRestrictionsForOrg(ctx context.Context, req *InteractionsRemoveRestrictionsForOrgReq, opt ...RequestOption) (*InteractionsRemoveRestrictionsForOrgResponse, error) {
	if req == nil {
		req = new(InteractionsRemoveRestrictionsForOrgReq)
	}
	resp := &InteractionsRemoveRestrictionsForOrgResponse{request: req}
	r, err := doRequest(ctx, req, "interactions/remove-restrictions-for-org", opt...)
	if r != nil {
		resp.response = *r
	}
	if err != nil {
		return resp, err
	}
	err = r.decodeBody(nil, "interactions/remove-restrictions-for-org")
	if err != nil {
		return nil, err
	}
	return resp, nil
}

/*
InteractionsRemoveRestrictionsForOrg performs requests for "interactions/remove-restrictions-for-org"

Remove interaction restrictions for an organization.

  DELETE /orgs/{org}/interaction-limits

https://developer.github.com/v3/interactions/orgs/#remove-interaction-restrictions-for-an-organization
*/
func (c Client) InteractionsRemoveRestrictionsForOrg(ctx context.Context, req *InteractionsRemoveRestrictionsForOrgReq, opt ...RequestOption) (*InteractionsRemoveRestrictionsForOrgResponse, error) {
	return InteractionsRemoveRestrictionsForOrg(ctx, req, append(c, opt...)...)
}

/*
InteractionsRemoveRestrictionsForOrgReq is request data for Client.InteractionsRemoveRestrictionsForOrg

https://developer.github.com/v3/interactions/orgs/#remove-interaction-restrictions-for-an-organization
*/
type InteractionsRemoveRestrictionsForOrgReq struct {
	_url string
	Org  string

	/*
	The Interactions API is currently in public preview. See the [blog
	post](https://developer.github.com/changes/2018-12-18-interactions-preview)
	preview for more details. To access the API during the preview period, you must
	set this to true.
	*/
	SombraPreview bool
}

func (r *InteractionsRemoveRestrictionsForOrgReq) url() string {
	return r._url
}

func (r *InteractionsRemoveRestrictionsForOrgReq) urlPath() string {
	return fmt.Sprintf("/orgs/%v/interaction-limits", r.Org)
}

func (r *InteractionsRemoveRestrictionsForOrgReq) method() string {
	return "DELETE"
}

func (r *InteractionsRemoveRestrictionsForOrgReq) urlQuery() url.Values {
	query := url.Values{}
	return query
}

func (r *InteractionsRemoveRestrictionsForOrgReq) header(requiredPreviews, allPreviews bool) http.Header {
	headerVals := map[string]*string{}
	previewVals := map[string]bool{"sombra": r.SombraPreview}
	if requiredPreviews {
		previewVals["sombra"] = true
	}
	if allPreviews {
		previewVals["sombra"] = true
	}
	return requestHeaders(headerVals, previewVals)
}

func (r *InteractionsRemoveRestrictionsForOrgReq) body() interface{} {
	return nil
}

func (r *InteractionsRemoveRestrictionsForOrgReq) dataStatuses() []int {
	return []int{}
}

func (r *InteractionsRemoveRestrictionsForOrgReq) validStatuses() []int {
	return []int{204}
}

// HTTPRequest builds an *http.Request
func (r *InteractionsRemoveRestrictionsForOrgReq) HTTPRequest(ctx context.Context, opt ...RequestOption) (*http.Request, error) {
	return buildHTTPRequest(ctx, r, "interactions/remove-restrictions-for-org", opt)
}

/*
Rel updates this request to point to a relative link from resp. Returns false if
the link does not exist. Handy for paging.
*/
func (r *InteractionsRemoveRestrictionsForOrgReq) Rel(link RelName, resp *InteractionsRemoveRestrictionsForOrgResponse) bool {
	u := resp.RelLink(link)
	if u == "" {
		return false
	}
	r._url = u
	return true
}

/*
InteractionsRemoveRestrictionsForOrgResponse is a response for InteractionsRemoveRestrictionsForOrg

https://developer.github.com/v3/interactions/orgs/#remove-interaction-restrictions-for-an-organization
*/
type InteractionsRemoveRestrictionsForOrgResponse struct {
	response
	request *InteractionsRemoveRestrictionsForOrgReq
}

/*
InteractionsRemoveRestrictionsForRepo performs requests for "interactions/remove-restrictions-for-repo"

Remove interaction restrictions for a repository.

  DELETE /repos/{owner}/{repo}/interaction-limits

https://developer.github.com/v3/interactions/repos/#remove-interaction-restrictions-for-a-repository
*/
func InteractionsRemoveRestrictionsForRepo(ctx context.Context, req *InteractionsRemoveRestrictionsForRepoReq, opt ...RequestOption) (*InteractionsRemoveRestrictionsForRepoResponse, error) {
	if req == nil {
		req = new(InteractionsRemoveRestrictionsForRepoReq)
	}
	resp := &InteractionsRemoveRestrictionsForRepoResponse{request: req}
	r, err := doRequest(ctx, req, "interactions/remove-restrictions-for-repo", opt...)
	if r != nil {
		resp.response = *r
	}
	if err != nil {
		return resp, err
	}
	err = r.decodeBody(nil, "interactions/remove-restrictions-for-repo")
	if err != nil {
		return nil, err
	}
	return resp, nil
}

/*
InteractionsRemoveRestrictionsForRepo performs requests for "interactions/remove-restrictions-for-repo"

Remove interaction restrictions for a repository.

  DELETE /repos/{owner}/{repo}/interaction-limits

https://developer.github.com/v3/interactions/repos/#remove-interaction-restrictions-for-a-repository
*/
func (c Client) InteractionsRemoveRestrictionsForRepo(ctx context.Context, req *InteractionsRemoveRestrictionsForRepoReq, opt ...RequestOption) (*InteractionsRemoveRestrictionsForRepoResponse, error) {
	return InteractionsRemoveRestrictionsForRepo(ctx, req, append(c, opt...)...)
}

/*
InteractionsRemoveRestrictionsForRepoReq is request data for Client.InteractionsRemoveRestrictionsForRepo

https://developer.github.com/v3/interactions/repos/#remove-interaction-restrictions-for-a-repository
*/
type InteractionsRemoveRestrictionsForRepoReq struct {
	_url  string
	Owner string
	Repo  string

	/*
	The Interactions API is currently in public preview. See the [blog
	post](https://developer.github.com/changes/2018-12-18-interactions-preview)
	preview for more details. To access the API during the preview period, you must
	set this to true.
	*/
	SombraPreview bool
}

func (r *InteractionsRemoveRestrictionsForRepoReq) url() string {
	return r._url
}

func (r *InteractionsRemoveRestrictionsForRepoReq) urlPath() string {
	return fmt.Sprintf("/repos/%v/%v/interaction-limits", r.Owner, r.Repo)
}

func (r *InteractionsRemoveRestrictionsForRepoReq) method() string {
	return "DELETE"
}

func (r *InteractionsRemoveRestrictionsForRepoReq) urlQuery() url.Values {
	query := url.Values{}
	return query
}

func (r *InteractionsRemoveRestrictionsForRepoReq) header(requiredPreviews, allPreviews bool) http.Header {
	headerVals := map[string]*string{}
	previewVals := map[string]bool{"sombra": r.SombraPreview}
	if requiredPreviews {
		previewVals["sombra"] = true
	}
	if allPreviews {
		previewVals["sombra"] = true
	}
	return requestHeaders(headerVals, previewVals)
}

func (r *InteractionsRemoveRestrictionsForRepoReq) body() interface{} {
	return nil
}

func (r *InteractionsRemoveRestrictionsForRepoReq) dataStatuses() []int {
	return []int{}
}

func (r *InteractionsRemoveRestrictionsForRepoReq) validStatuses() []int {
	return []int{204}
}

// HTTPRequest builds an *http.Request
func (r *InteractionsRemoveRestrictionsForRepoReq) HTTPRequest(ctx context.Context, opt ...RequestOption) (*http.Request, error) {
	return buildHTTPRequest(ctx, r, "interactions/remove-restrictions-for-repo", opt)
}

/*
Rel updates this request to point to a relative link from resp. Returns false if
the link does not exist. Handy for paging.
*/
func (r *InteractionsRemoveRestrictionsForRepoReq) Rel(link RelName, resp *InteractionsRemoveRestrictionsForRepoResponse) bool {
	u := resp.RelLink(link)
	if u == "" {
		return false
	}
	r._url = u
	return true
}

/*
InteractionsRemoveRestrictionsForRepoResponse is a response for InteractionsRemoveRestrictionsForRepo

https://developer.github.com/v3/interactions/repos/#remove-interaction-restrictions-for-a-repository
*/
type InteractionsRemoveRestrictionsForRepoResponse struct {
	response
	request *InteractionsRemoveRestrictionsForRepoReq
}

/*
InteractionsSetRestrictionsForOrg performs requests for "interactions/set-restrictions-for-org"

Set interaction restrictions for an organization.

  PUT /orgs/{org}/interaction-limits

https://developer.github.com/v3/interactions/orgs/#set-interaction-restrictions-for-an-organization
*/
func InteractionsSetRestrictionsForOrg(ctx context.Context, req *InteractionsSetRestrictionsForOrgReq, opt ...RequestOption) (*InteractionsSetRestrictionsForOrgResponse, error) {
	if req == nil {
		req = new(InteractionsSetRestrictionsForOrgReq)
	}
	resp := &InteractionsSetRestrictionsForOrgResponse{request: req}
	r, err := doRequest(ctx, req, "interactions/set-restrictions-for-org", opt...)
	if r != nil {
		resp.response = *r
	}
	if err != nil {
		return resp, err
	}
	resp.Data = components.InteractionLimit{}
	err = r.decodeBody(&resp.Data, "interactions/set-restrictions-for-org")
	if err != nil {
		return nil, err
	}
	return resp, nil
}

/*
InteractionsSetRestrictionsForOrg performs requests for "interactions/set-restrictions-for-org"

Set interaction restrictions for an organization.

  PUT /orgs/{org}/interaction-limits

https://developer.github.com/v3/interactions/orgs/#set-interaction-restrictions-for-an-organization
*/
func (c Client) InteractionsSetRestrictionsForOrg(ctx context.Context, req *InteractionsSetRestrictionsForOrgReq, opt ...RequestOption) (*InteractionsSetRestrictionsForOrgResponse, error) {
	return InteractionsSetRestrictionsForOrg(ctx, req, append(c, opt...)...)
}

/*
InteractionsSetRestrictionsForOrgReq is request data for Client.InteractionsSetRestrictionsForOrg

https://developer.github.com/v3/interactions/orgs/#set-interaction-restrictions-for-an-organization
*/
type InteractionsSetRestrictionsForOrgReq struct {
	_url        string
	Org         string
	RequestBody InteractionsSetRestrictionsForOrgReqBody

	/*
	The Interactions API is currently in public preview. See the [blog
	post](https://developer.github.com/changes/2018-12-18-interactions-preview)
	preview for more details. To access the API during the preview period, you must
	set this to true.
	*/
	SombraPreview bool
}

func (r *InteractionsSetRestrictionsForOrgReq) url() string {
	return r._url
}

func (r *InteractionsSetRestrictionsForOrgReq) urlPath() string {
	return fmt.Sprintf("/orgs/%v/interaction-limits", r.Org)
}

func (r *InteractionsSetRestrictionsForOrgReq) method() string {
	return "PUT"
}

func (r *InteractionsSetRestrictionsForOrgReq) urlQuery() url.Values {
	query := url.Values{}
	return query
}

func (r *InteractionsSetRestrictionsForOrgReq) header(requiredPreviews, allPreviews bool) http.Header {
	headerVals := map[string]*string{
		"accept":       String("application/json"),
		"content-type": String("application/json"),
	}
	previewVals := map[string]bool{"sombra": r.SombraPreview}
	if requiredPreviews {
		previewVals["sombra"] = true
	}
	if allPreviews {
		previewVals["sombra"] = true
	}
	return requestHeaders(headerVals, previewVals)
}

func (r *InteractionsSetRestrictionsForOrgReq) body() interface{} {
	return r.RequestBody
}

func (r *InteractionsSetRestrictionsForOrgReq) dataStatuses() []int {
	return []int{200}
}

func (r *InteractionsSetRestrictionsForOrgReq) validStatuses() []int {
	return []int{200}
}

// HTTPRequest builds an *http.Request
func (r *InteractionsSetRestrictionsForOrgReq) HTTPRequest(ctx context.Context, opt ...RequestOption) (*http.Request, error) {
	return buildHTTPRequest(ctx, r, "interactions/set-restrictions-for-org", opt)
}

/*
Rel updates this request to point to a relative link from resp. Returns false if
the link does not exist. Handy for paging.
*/
func (r *InteractionsSetRestrictionsForOrgReq) Rel(link RelName, resp *InteractionsSetRestrictionsForOrgResponse) bool {
	u := resp.RelLink(link)
	if u == "" {
		return false
	}
	r._url = u
	return true
}

/*
InteractionsSetRestrictionsForOrgReqBody is a request body for interactions/set-restrictions-for-org

https://developer.github.com/v3/interactions/orgs/#set-interaction-restrictions-for-an-organization
*/
type InteractionsSetRestrictionsForOrgReqBody struct {

	/*
	Specifies the group of GitHub users who can comment, open issues, or create pull
	requests in public repositories for the given organization. Must be one of:
	`existing_users`, `contributors_only`, or `collaborators_only`.
	*/
	Limit *string `json:"limit"`
}

/*
InteractionsSetRestrictionsForOrgResponse is a response for InteractionsSetRestrictionsForOrg

https://developer.github.com/v3/interactions/orgs/#set-interaction-restrictions-for-an-organization
*/
type InteractionsSetRestrictionsForOrgResponse struct {
	response
	request *InteractionsSetRestrictionsForOrgReq
	Data    components.InteractionLimit
}

/*
InteractionsSetRestrictionsForRepo performs requests for "interactions/set-restrictions-for-repo"

Set interaction restrictions for a repository.

  PUT /repos/{owner}/{repo}/interaction-limits

https://developer.github.com/v3/interactions/repos/#set-interaction-restrictions-for-a-repository
*/
func InteractionsSetRestrictionsForRepo(ctx context.Context, req *InteractionsSetRestrictionsForRepoReq, opt ...RequestOption) (*InteractionsSetRestrictionsForRepoResponse, error) {
	if req == nil {
		req = new(InteractionsSetRestrictionsForRepoReq)
	}
	resp := &InteractionsSetRestrictionsForRepoResponse{request: req}
	r, err := doRequest(ctx, req, "interactions/set-restrictions-for-repo", opt...)
	if r != nil {
		resp.response = *r
	}
	if err != nil {
		return resp, err
	}
	resp.Data = components.InteractionLimit{}
	err = r.decodeBody(&resp.Data, "interactions/set-restrictions-for-repo")
	if err != nil {
		return nil, err
	}
	return resp, nil
}

/*
InteractionsSetRestrictionsForRepo performs requests for "interactions/set-restrictions-for-repo"

Set interaction restrictions for a repository.

  PUT /repos/{owner}/{repo}/interaction-limits

https://developer.github.com/v3/interactions/repos/#set-interaction-restrictions-for-a-repository
*/
func (c Client) InteractionsSetRestrictionsForRepo(ctx context.Context, req *InteractionsSetRestrictionsForRepoReq, opt ...RequestOption) (*InteractionsSetRestrictionsForRepoResponse, error) {
	return InteractionsSetRestrictionsForRepo(ctx, req, append(c, opt...)...)
}

/*
InteractionsSetRestrictionsForRepoReq is request data for Client.InteractionsSetRestrictionsForRepo

https://developer.github.com/v3/interactions/repos/#set-interaction-restrictions-for-a-repository
*/
type InteractionsSetRestrictionsForRepoReq struct {
	_url        string
	Owner       string
	Repo        string
	RequestBody InteractionsSetRestrictionsForRepoReqBody

	/*
	The Interactions API is currently in public preview. See the [blog
	post](https://developer.github.com/changes/2018-12-18-interactions-preview)
	preview for more details. To access the API during the preview period, you must
	set this to true.
	*/
	SombraPreview bool
}

func (r *InteractionsSetRestrictionsForRepoReq) url() string {
	return r._url
}

func (r *InteractionsSetRestrictionsForRepoReq) urlPath() string {
	return fmt.Sprintf("/repos/%v/%v/interaction-limits", r.Owner, r.Repo)
}

func (r *InteractionsSetRestrictionsForRepoReq) method() string {
	return "PUT"
}

func (r *InteractionsSetRestrictionsForRepoReq) urlQuery() url.Values {
	query := url.Values{}
	return query
}

func (r *InteractionsSetRestrictionsForRepoReq) header(requiredPreviews, allPreviews bool) http.Header {
	headerVals := map[string]*string{
		"accept":       String("application/json"),
		"content-type": String("application/json"),
	}
	previewVals := map[string]bool{"sombra": r.SombraPreview}
	if requiredPreviews {
		previewVals["sombra"] = true
	}
	if allPreviews {
		previewVals["sombra"] = true
	}
	return requestHeaders(headerVals, previewVals)
}

func (r *InteractionsSetRestrictionsForRepoReq) body() interface{} {
	return r.RequestBody
}

func (r *InteractionsSetRestrictionsForRepoReq) dataStatuses() []int {
	return []int{200}
}

func (r *InteractionsSetRestrictionsForRepoReq) validStatuses() []int {
	return []int{200}
}

// HTTPRequest builds an *http.Request
func (r *InteractionsSetRestrictionsForRepoReq) HTTPRequest(ctx context.Context, opt ...RequestOption) (*http.Request, error) {
	return buildHTTPRequest(ctx, r, "interactions/set-restrictions-for-repo", opt)
}

/*
Rel updates this request to point to a relative link from resp. Returns false if
the link does not exist. Handy for paging.
*/
func (r *InteractionsSetRestrictionsForRepoReq) Rel(link RelName, resp *InteractionsSetRestrictionsForRepoResponse) bool {
	u := resp.RelLink(link)
	if u == "" {
		return false
	}
	r._url = u
	return true
}

/*
InteractionsSetRestrictionsForRepoReqBody is a request body for interactions/set-restrictions-for-repo

https://developer.github.com/v3/interactions/repos/#set-interaction-restrictions-for-a-repository
*/
type InteractionsSetRestrictionsForRepoReqBody struct {

	/*
	Specifies the group of GitHub users who can comment, open issues, or create pull
	requests for the given repository. Must be one of: `existing_users`,
	`contributors_only`, or `collaborators_only`.
	*/
	Limit *string `json:"limit"`
}

/*
InteractionsSetRestrictionsForRepoResponse is a response for InteractionsSetRestrictionsForRepo

https://developer.github.com/v3/interactions/repos/#set-interaction-restrictions-for-a-repository
*/
type InteractionsSetRestrictionsForRepoResponse struct {
	response
	request *InteractionsSetRestrictionsForRepoReq
	Data    components.InteractionLimit
}
