// Code generated by octo-go; DO NOT EDIT.

package internal

const (
	AttrRedirectOnly EndpointAttribute = iota
	AttrBoolean
	AttrBodyUploader
	AttrJSONRequestBody
	AttrExplicitURL
	AttrNoResponseBody
)
