name: applytemplate
on: [push]
jobs:
  applytemplate:
    runs-on: ubuntu-18.04
    if: github.repository != 'WillAbides/goproject-tmpl' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: script/apply-template
      - uses: peter-evans/create-pull-request@v2
        with:
          branch: applytemplate/patch
          title: update repository template
          commit-message: update repository template with new name
          body: This updates various bits of this repository with its name instead of the placeholders from the template.
