name: update-schema
on:
  schedule:
    - cron: '41 * * * *'
  workflow_dispatch: {}
jobs:
  update-schema:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OCTO_CLI_BOT_TOKEN }}
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - run: script/new-schema-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
